name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/_lint.yaml

  test:
    uses: ./.github/workflows/_tests.yaml

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder for end-to-end tests
        run: echo "End-to-end and browser tests would run here"

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder for documentation generation
        run: echo "Documentation generation like storybook would run here"

  performance:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder for performance tests
        run: echo "Performance like Lighthouse tests would run here"
