name: Prettier
on:
  pull_request:
  push:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: |
          yarn
          yarn prettier . --write
          yarn eslint . --ext .js,.jsx,.ts,.tsx --fix
      - uses: autofix-ci/action@v1
        with:
          commit-message: "Auto fix: Prettier & ESLint"
